#!/bin/bash
# lib/config.sh - Configuration management functions for Confluent Cloud utilities

# Source common functions
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/common.sh
source "$SCRIPT_DIR/common.sh"

# Default environment file location
DEFAULT_ENV_FILE=".env"

# Load environment configuration
load_env() {
    local env_file="${CC_ENV_FILE:-$DEFAULT_ENV_FILE}"
    
    if [[ ! -f "$env_file" ]]; then
        error "Environment file not found: $env_file"
        info "Copy .env.example to $env_file and configure your settings"
        return 1
    fi
    
    # Source the environment file
    set -a  # automatically export all variables
    # shellcheck source=/dev/null
    source "$env_file"
    set +a
    
    debug "Loaded environment from: $env_file"
    return 0
}

# Validate required environment variables
validate_env() {
    local required_vars=(
        "CONFLUENT_CLOUD_API_KEY"
        "CONFLUENT_CLOUD_API_SECRET"
        "CONFLUENT_ENVIRONMENT_ID"
        "CONFLUENT_CLUSTER_ID"
    )
    
    local missing_vars=()
    
    for var in "${required_vars[@]}"; do
        if [[ -z "${!var}" ]]; then
            missing_vars+=("$var")
        fi
    done
    
    if [[ ${#missing_vars[@]} -gt 0 ]]; then
        error "Missing required environment variables:"
        for var in "${missing_vars[@]}"; do
            echo -e "  ${RED}${ERROR}${RESET} $var"
        done
        info "Please configure these variables in your .env file"
        return 1
    fi
    
    success "All required environment variables are set"
    return 0
}

# Validate optional environment variables and set defaults
validate_optional_env() {
    # Set default bootstrap servers if not provided
    if [[ -z "$CONFLUENT_BOOTSTRAP_SERVERS" && -n "$CONFLUENT_CLUSTER_ID" ]]; then
        local cluster_id="$CONFLUENT_CLUSTER_ID"
        local region="${CONFLUENT_REGION:-us-east-2}"
        local cloud="${CONFLUENT_CLOUD:-aws}"
        
        case "$cloud" in
            aws)
                CONFLUENT_BOOTSTRAP_SERVERS="${cluster_id}.${region}.aws.confluent.cloud:9092"
                ;;
            gcp)
                CONFLUENT_BOOTSTRAP_SERVERS="${cluster_id}.${region}.gcp.confluent.cloud:9092"
                ;;
            azure)
                CONFLUENT_BOOTSTRAP_SERVERS="${cluster_id}.${region}.azure.confluent.cloud:9092"
                ;;
            *)
                warning "Unknown cloud provider: $cloud. Bootstrap servers not auto-generated."
                ;;
        esac
        
        if [[ -n "$CONFLUENT_BOOTSTRAP_SERVERS" ]]; then
            debug "Auto-generated bootstrap servers: $CONFLUENT_BOOTSTRAP_SERVERS"
        fi
    fi
    
    # Validate Schema Registry configuration if provided
    if [[ -n "$CONFLUENT_SCHEMA_REGISTRY_URL" ]]; then
        if [[ -z "$CONFLUENT_SCHEMA_REGISTRY_API_KEY" || -z "$CONFLUENT_SCHEMA_REGISTRY_API_SECRET" ]]; then
            warning "Schema Registry URL provided but API credentials are missing"
        fi
    fi
}

# Generate Java properties configuration
generate_java_properties() {
    local output_file="$1"
    local template_type="${2:-client}"  # client, producer, consumer
    
    if [[ -z "$output_file" ]]; then
        error "Output file not specified for Java properties generation"
        return 1
    fi
    
    progress "Generating Java properties file: $output_file"
    
    cat > "$output_file" << EOF
# Generated by cc-config-generate on $(date)
# Template type: $template_type

# Kafka Cluster Configuration
bootstrap.servers=${CONFLUENT_BOOTSTRAP_SERVERS}
security.protocol=SASL_SSL
sasl.mechanism=PLAIN
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required \\
    username='${CONFLUENT_CLOUD_API_KEY}' \\
    password='${CONFLUENT_CLOUD_API_SECRET}';

# Client Configuration
client.id=${CONFLUENT_CLIENT_ID:-cc-tools-client}

EOF

    # Add template-specific configurations
    case "$template_type" in
        producer)
            cat >> "$output_file" << EOF
# Producer Configuration
acks=all
retries=2147483647
max.in.flight.requests.per.connection=5
enable.idempotence=true
compression.type=snappy
batch.size=16384
linger.ms=5

EOF
            ;;
        consumer)
            cat >> "$output_file" << EOF
# Consumer Configuration
group.id=${CONFLUENT_CONSUMER_GROUP:-cc-tools-consumer-group}
auto.offset.reset=earliest
enable.auto.commit=true
auto.commit.interval.ms=5000

EOF
            ;;
    esac
    
    # Add Schema Registry configuration if available
    if [[ -n "$CONFLUENT_SCHEMA_REGISTRY_URL" ]]; then
        cat >> "$output_file" << EOF
# Schema Registry Configuration
schema.registry.url=${CONFLUENT_SCHEMA_REGISTRY_URL}
schema.registry.basic.auth.user.info=${CONFLUENT_SCHEMA_REGISTRY_API_KEY}:${CONFLUENT_SCHEMA_REGISTRY_API_SECRET}

EOF
    fi
    
    success "Generated Java properties: $output_file"
    return 0
}

# Generate Python configuration
generate_python_config() {
    local output_file="$1"
    local format="${2:-env}"  # env, properties, json
    
    if [[ -z "$output_file" ]]; then
        error "Output file not specified for Python configuration generation"
        return 1
    fi
    
    progress "Generating Python configuration file: $output_file"
    
    case "$format" in
        env)
            cat > "$output_file" << EOF
# Generated by cc-config-generate on $(date)
# Python environment configuration

BOOTSTRAP_SERVERS=${CONFLUENT_BOOTSTRAP_SERVERS}
SECURITY_PROTOCOL=SASL_SSL
SASL_MECHANISM=PLAIN
SASL_USERNAME=${CONFLUENT_CLOUD_API_KEY}
SASL_PASSWORD=${CONFLUENT_CLOUD_API_SECRET}
CLIENT_ID=${CONFLUENT_CLIENT_ID:-cc-tools-python-client}

EOF
            if [[ -n "$CONFLUENT_SCHEMA_REGISTRY_URL" ]]; then
                cat >> "$output_file" << EOF
SCHEMA_REGISTRY_URL=${CONFLUENT_SCHEMA_REGISTRY_URL}
SCHEMA_REGISTRY_API_KEY=${CONFLUENT_SCHEMA_REGISTRY_API_KEY}
SCHEMA_REGISTRY_API_SECRET=${CONFLUENT_SCHEMA_REGISTRY_API_SECRET}

EOF
            fi
            ;;
        properties)
            cat > "$output_file" << EOF
# Generated by cc-config-generate on $(date)
# Python client properties

bootstrap.servers=${CONFLUENT_BOOTSTRAP_SERVERS}
security.protocol=SASL_SSL
sasl.mechanism=PLAIN
sasl.username=${CONFLUENT_CLOUD_API_KEY}
sasl.password=${CONFLUENT_CLOUD_API_SECRET}
client.id=${CONFLUENT_CLIENT_ID:-cc-tools-python-client}

EOF
            ;;
        json)
            cat > "$output_file" << EOF
{
  "bootstrap.servers": "${CONFLUENT_BOOTSTRAP_SERVERS}",
  "security.protocol": "SASL_SSL",
  "sasl.mechanism": "PLAIN",
  "sasl.username": "${CONFLUENT_CLOUD_API_KEY}",
  "sasl.password": "${CONFLUENT_CLOUD_API_SECRET}",
  "client.id": "${CONFLUENT_CLIENT_ID:-cc-tools-python-client}"$(if [[ -n "$CONFLUENT_SCHEMA_REGISTRY_URL" ]]; then echo ',
  "schema.registry.url": "'"$CONFLUENT_SCHEMA_REGISTRY_URL"'",
  "schema.registry.basic.auth.user.info": "'"$CONFLUENT_SCHEMA_REGISTRY_API_KEY"':'"$CONFLUENT_SCHEMA_REGISTRY_API_SECRET"'"'; fi)
}
EOF
            ;;
    esac
    
    success "Generated Python configuration: $output_file"
    return 0
}

# Generate Node.js configuration
generate_nodejs_config() {
    local output_file="$1"
    local format="${2:-env}"  # env, json
    
    if [[ -z "$output_file" ]]; then
        error "Output file not specified for Node.js configuration generation"
        return 1
    fi
    
    progress "Generating Node.js configuration file: $output_file"
    
    case "$format" in
        env)
            cat > "$output_file" << EOF
# Generated by cc-config-generate on $(date)
# Node.js environment configuration

KAFKA_BOOTSTRAP_SERVERS=${CONFLUENT_BOOTSTRAP_SERVERS}
KAFKA_SECURITY_PROTOCOL=SASL_SSL
KAFKA_SASL_MECHANISM=PLAIN
KAFKA_SASL_USERNAME=${CONFLUENT_CLOUD_API_KEY}
KAFKA_SASL_PASSWORD=${CONFLUENT_CLOUD_API_SECRET}
KAFKA_CLIENT_ID=${CONFLUENT_CLIENT_ID:-cc-tools-nodejs-client}

EOF
            if [[ -n "$CONFLUENT_SCHEMA_REGISTRY_URL" ]]; then
                cat >> "$output_file" << EOF
SCHEMA_REGISTRY_URL=${CONFLUENT_SCHEMA_REGISTRY_URL}
SCHEMA_REGISTRY_API_KEY=${CONFLUENT_SCHEMA_REGISTRY_API_KEY}
SCHEMA_REGISTRY_API_SECRET=${CONFLUENT_SCHEMA_REGISTRY_API_SECRET}

EOF
            fi
            ;;
        json)
            cat > "$output_file" << EOF
{
  "kafka": {
    "brokers": ["${CONFLUENT_BOOTSTRAP_SERVERS}"],
    "ssl": true,
    "sasl": {
      "mechanism": "plain",
      "username": "${CONFLUENT_CLOUD_API_KEY}",
      "password": "${CONFLUENT_CLOUD_API_SECRET}"
    },
    "clientId": "${CONFLUENT_CLIENT_ID:-cc-tools-nodejs-client}"
  }$(if [[ -n "$CONFLUENT_SCHEMA_REGISTRY_URL" ]]; then echo ',
  "schemaRegistry": {
    "url": "'"$CONFLUENT_SCHEMA_REGISTRY_URL"'",
    "auth": {
      "username": "'"$CONFLUENT_SCHEMA_REGISTRY_API_KEY"'",
      "password": "'"$CONFLUENT_SCHEMA_REGISTRY_API_SECRET"'"
    }
  }'; fi)
}
EOF
            ;;
    esac
    
    success "Generated Node.js configuration: $output_file"
    return 0
}

# Generate Docker environment file
generate_docker_config() {
    local output_file="$1"
    
    if [[ -z "$output_file" ]]; then
        error "Output file not specified for Docker configuration generation"
        return 1
    fi
    
    progress "Generating Docker environment file: $output_file"
    
    cat > "$output_file" << EOF
# Generated by cc-config-generate on $(date)
# Docker environment configuration

KAFKA_BOOTSTRAP_SERVERS=${CONFLUENT_BOOTSTRAP_SERVERS}
KAFKA_SECURITY_PROTOCOL=SASL_SSL
KAFKA_SASL_MECHANISM=PLAIN
KAFKA_SASL_USERNAME=${CONFLUENT_CLOUD_API_KEY}
KAFKA_SASL_PASSWORD=${CONFLUENT_CLOUD_API_SECRET}
KAFKA_CLIENT_ID=${CONFLUENT_CLIENT_ID:-cc-tools-docker-client}

CONFLUENT_ENVIRONMENT_ID=${CONFLUENT_ENVIRONMENT_ID}
CONFLUENT_CLUSTER_ID=${CONFLUENT_CLUSTER_ID}
CONFLUENT_REGION=${CONFLUENT_REGION}
CONFLUENT_CLOUD=${CONFLUENT_CLOUD}

EOF
    
    if [[ -n "$CONFLUENT_SCHEMA_REGISTRY_URL" ]]; then
        cat >> "$output_file" << EOF
SCHEMA_REGISTRY_URL=${CONFLUENT_SCHEMA_REGISTRY_URL}
SCHEMA_REGISTRY_API_KEY=${CONFLUENT_SCHEMA_REGISTRY_API_KEY}
SCHEMA_REGISTRY_API_SECRET=${CONFLUENT_SCHEMA_REGISTRY_API_SECRET}

EOF
    fi
    
    success "Generated Docker configuration: $output_file"
    return 0
}

# Get configuration value by key
get_config() {
    local key="$1"
    local default_value="${2:-}"
    
    case "$key" in
        api_key|api-key)
            echo "${CONFLUENT_CLOUD_API_KEY:-$default_value}"
            ;;
        api_secret|api-secret)
            echo "${CONFLUENT_CLOUD_API_SECRET:-$default_value}"
            ;;
        environment|env)
            echo "${CONFLUENT_ENVIRONMENT_ID:-$default_value}"
            ;;
        cluster)
            echo "${CONFLUENT_CLUSTER_ID:-$default_value}"
            ;;
        bootstrap_servers|bootstrap-servers)
            echo "${CONFLUENT_BOOTSTRAP_SERVERS:-$default_value}"
            ;;
        schema_registry_url|schema-registry-url)
            echo "${CONFLUENT_SCHEMA_REGISTRY_URL:-$default_value}"
            ;;
        region)
            echo "${CONFLUENT_REGION:-$default_value}"
            ;;
        cloud)
            echo "${CONFLUENT_CLOUD:-$default_value}"
            ;;
        *)
            echo "$default_value"
            ;;
    esac
}

# Validate TableFlow environment variables
validate_tableflow_env() {
    local required_vars=(
        "CC_TF_API_KEY"
        "CC_TF_API_SECRET"
        "CC_ORG_ID"
        "CC_ENV"
        "CONFLUENT_REGION"
    )
    
    local missing_vars=()
    
    for var in "${required_vars[@]}"; do
        if [[ -z "${!var}" ]]; then
            missing_vars+=("$var")
        fi
    done
    
    if [[ ${#missing_vars[@]} -gt 0 ]]; then
        error "Missing required TableFlow environment variables:"
        for var in "${missing_vars[@]}"; do
            echo -e "  ${RED}${ERROR}${RESET} $var"
        done
        info "Please configure these variables in your .env file"
        return 1
    fi
    
    success "All required TableFlow environment variables are set"
    return 0
}

# Generate TableFlow catalog URL
generate_tableflow_catalog_url() {
    local region="${CONFLUENT_REGION:-us-west-2}"
    local org_id="${CC_ORG_ID}"
    local env_id="${CC_ENV}"
    
    if [[ -z "$org_id" || -z "$env_id" ]]; then
        error "Organization ID and Environment ID are required to generate TableFlow catalog URL"
        return 1
    fi
    
    echo "https://tableflow.${region}.aws.confluent.cloud/iceberg/catalog/organizations/${org_id}/environments/${env_id}"
}

# Generate TableFlow properties file
generate_tableflow_properties() {
    local output_file="$1"
    local connector_name="${2:-iceberg}"
    
    if [[ -z "$output_file" ]]; then
        error "Output file not specified for TableFlow properties generation"
        return 1
    fi
    
    # Validate required environment variables
    validate_tableflow_env || return 1
    
    # Generate catalog URL if not provided
    local catalog_url="${CC_TF_CATALOG_URL}"
    if [[ -z "$catalog_url" ]]; then
        catalog_url=$(generate_tableflow_catalog_url)
        if [[ $? -ne 0 ]]; then
            return 1
        fi
    fi
    
    progress "Generating TableFlow properties file: $output_file"
    
    cat > "$output_file" << EOF
# Generated by cc-tableflow-properties on $(date)
# TableFlow Iceberg Connector Configuration

# Connector Configuration
connector.name=${connector_name}

# Iceberg Catalog Configuration
iceberg.catalog.type=rest
iceberg.rest-catalog.oauth2.credential=${CC_TF_API_KEY}:${CC_TF_API_SECRET}
iceberg.rest-catalog.security=OAUTH2
iceberg.rest-catalog.uri=${catalog_url}
iceberg.rest-catalog.vended-credentials-enabled=true

# File System Configuration
fs.native-s3.enabled=true
s3.region=${CONFLUENT_REGION:-us-west-2}

# Security Configuration
iceberg.security=read_only
EOF
    
    success "Generated TableFlow properties: $output_file"
    return 0
}

# Initialize configuration
init_config() {
    load_env || return 1
    validate_env || return 1
    validate_optional_env
    return 0
}

# Initialize TableFlow configuration
init_tableflow_config() {
    load_env || return 1
    validate_tableflow_env || return 1
    return 0
}
